config/routes.rb
AjaxDemo::Application.routes.draw do
  root :to => "Users#new"

  resources :secrets
  resource :session
  resources :users
  resources :users do 
    resource :secrets, only: [:new, :create]
  end
  
  resources :todo_lists
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :title

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  validates :title, :author, :recipient, :presence => true
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  attr_accessible :name, :todo_list_id
  
  belongs_to :todo_list,
  :foreign_key => :todo_list_id
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  attr_accessible :title, :user_id
  
  belongs_to :user,
  :foreign_key => :user_id
  
  has_many :todo_items
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password
  
  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => "author_id"
  )
  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => "recipient_id"
  )
  
  has_many :todo_lists,
  :foreign_key => :user_id
  
  has_many :todo_items,
  :through => :todo_lists,
  :source => :todo_items
  
  validates :username, :password_digest, :presence => true
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def index
    respond_to do |format|
      format.html { render :index }
      format.json { render :json => Secret.all }
    end
  end
  
  def new
    @secret = Secret.new
  end

  def create
    @secret = Secret.create!(params[:secret])

    respond_to do |format|
      format.json { render :json => @secret }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user_attributes = params[:user]
    @user = login_user(
      user_attributes[:username],
      user_attributes[:password]
    )
    
    if @user
      redirect_to user_url(@user)
    else
      @user = User.new(user_attributes)
      render :new
    end
  end

  def new
    @user = User.new
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  
  def index
    @user = current_user
    @lists = @user.todo_lists
    @list = TodoList.new
  end
  
  def create
    @list = TodoList.new(params[:todo_list])
    current_user.todo_lists << @list
    render :json => @list
  end
  
  def destroy
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(params[:user])
    redirect_to user_url(@user)
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return nil if session[:session_token].nil?

    User.find_by_session_token(session[:session_token])
  end

  def login_user(username, password)
    u = User.find_by_username(username)

    return nil if u.nil?
    return nil unless BCrypt::Password.new(u.password_digest) == password

    u.session_token = SecureRandom::urlsafe_base64(32)
    u.save!
    session[:session_token] = u.session_token

    u
  end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	<%#= link_to "Your TODO Lists", todo_lists_url, :method => :get %>
  <%= yield %>
</body>
</html>

app/views/todo_lists/_lists.html.erb
<script>
<div class='todo-list' id=<%= id%>
</div>
</script>

app/views/todo_lists/_new_list_form.html.erb
<%= form_for(@list, :remote => true) do |f| %>
	<%= f.label :title, "New list" %>:
	<%= f.text_field :title %>
	<br>
	<%= f.submit %>
<% end %>

app/views/todo_lists/index.html.erb
<!-- <h1> <%#= @user.username.capitalize %>'s todo lists:</h1> -->
<!-- hardcoded into index.html.erb
<div>
	<ol>
	<% @lists.each do |list| %>
	
		<li> <%= list.title %></li>
		<ul>
			<% list.todo_items.each do |item| %>
			<li><%= item.name %></li>
			<%  end %>
		</ul>
		<br>
	
	<% end %>
	</ol>
</div> -->

<%= form_for(@list, :remote => true) do |f| %>
	<%= f.label :title, "New list" %>:
	<%= f.text_field :title %>
	<br>
	<%= f.submit %>
<% end %>

<script type="application/json" id="lists">
<% ActiveRecord::Base.include_root_in_json = true %>
<%= @user.todo_lists.to_json(:include => :todo_items).html_safe %>
</script>

	

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<ul>
  <% @user.received_secrets.each do |secret| %>
    <li><%= secret.title %></li>
  <% end %>
</ul>